SELECT CHDRNUM, STATCODE,TRANNO, CURRFROM FROM TDEVDTA.CHDRPF
WHERE CHDRNUM = '22046500'
;
SELECT CHDRNO,TRANNO, DTEEFF, DTEATT FROM TDEVDTA.RMOTPF
WHERE CHDRNO = '22046500'
;

SELECT * FROM TABLE(PJ_ITEM_LOOKUP('T1698','')) AS X
;

SELECT * FROM TSITWRK.BLOG188183
